### ISSUE TITLE
Peer Review - 4X4

### ISSUE THREAD

**Issue by jaelynkapuaioane** [INFO-526-FA24/project-2-pixels-patterns#1]
1. Kapua Ioane - jaelynkapuaioane
   Tanmay Naik - tanmaynaik11
   Krisha Vardhni Mahesh - KrishaVM 
   Nikhil Badgujar - bnikhil

2. The goal of the project is to analyze data from Formula 1 races throughout different seasons and tracks.

3. The data used is the f1DataR package, which provides data on race results, drivers, and other miscellaneous information. Because of the complexity of motorsports, performing an analysis can be really tricky. Using the f1DataR package hopes to simplify this.

4.  There are four research questions - 
- How can we visualize the race winners on the Circuit de Monaco over the past four years (2019-2023) in a clear and insightful way using R?
-Using the f1dataR package in R, how can you analyze and visualize a Formula 1 driver’s performance by plotting their speed and throttle data during a lap? What insights can be gained from these visualizations?
-How do each F1 team’s lap times improve over the course of a race, and how do these improvements compare across different circuit types?
-What is the relationship between pit stop timing and overall race position for top teams?

Question 1 will be visualized with a bar and donut, Question 2 and 3 is a line plot, and Question 4 is a scatter plot.

5. Is f1DataR a library or a dataset? This is a little unclear. Please clarify this within the proposal.  

   Does any data wrangling need to happen within the dataset in order to answer your question?

   Under each question, you have listed things like "load_driver_telemetry" - what are these? Are these functions you have written? Are these provided by the dataset?

6. This project heavily mirrors project 1 in terms of structure and flow - the only difference seems to be using a different dataset. It might be better to explore topics outside of what has already been proposed beyond just a new dataset.

7. It's been established that due to the complexity of motorsports, data analysis is difficult. The process of overcoming this difficulty should be highlighted as well as new insights by doing so.

8. Repo Structure Not Provided within Proposal

9. It seems like you have 1 question per person - this can make your project seem a little disconnected. Make sure to work with groupmates to have a cohesive story within the project.

**Comment by sindhugoshika** [comment]
Hello Team 4X4,

Thank you for your valuable review!

#5 and #8:
f1dataR is an R library, not a dataset. We are employing data wrangling in our project to clean and prepare the fetched data. Additionally, functions like load_driver_telemetry are pre-defined utilities within the library that simplify access to specific datasets, such as driver telemetry or race statistics. This has been noted in the proposal, and we’ve updated the repository structure as per your suggestion.

#6, #7, and #9:
While our project flow and structure may share similarities with Project 1, this time we are working with live data and plan to incorporate enhanced and 3D visualizations. We are committed to ensuring that our visualizations effectively highlight our contributions.

It’s true that we initially structured the project with one question per person to give everyone a chance to work independently. However, we value your feedback and will aim to present the project cohesively, weaving our individual contributions into a unified story.

Thank you,
Team Pixels and Patterns
