### ISSUE TITLE
Review from Visual Voyagers

### ISSUE THREAD

**Issue by Tusharvimal** [INFO-526-FA24/project-2-pixels-patterns#10]
1. What is the good thing in the poster?
The Dataset and visualzation shown are pretty impressive and clearly shows which factor are important in a F1 race.

2. What do you think can/should be improved?
The layout of the poster is not that clear and is confusing.

**Comment by sindhugoshika** [comment]
Hello Team,

Thank you for your kind words and valuable feedback. We have carefully reviewed the layout of the poster and made sure to arrange it more clearly for the showcase day. Your input is much appreciated, and we are confident that the updated layout had improved the presentation.

Thank you again!

Best regards,
Team Pixels and Patterns
