### ISSUE TITLE
Proposal Peer review

### ISSUE THREAD

**Issue by gr98765** [INFO-526-FA24/project-2-pixels-patterns#2]
1.Team Name: Visual Voyagers
Team Members: Gaurangi raul, Viren Sasalu, Tushar Vimal, Bhaskar Bijoy Kashyap @gr98765 @Tusharvimal @virensasalu @bhaskar-237

2.Goal of the project:
The goal of this project is to analyze the F1 dataset to understand F1 races outcomes in multiple seasons
It aims to offer a deeper understanding of race outcomes, driver performance, and trends across different seasons, with a particular focus on specific Grand Prix events. This analysis can benefit teams, fans, and potential sponsors interested in understanding the factors that impact success in racing.

3.Describe the data used:
The data used here is F1dataR package, it is a historical data which provides access to race results, driver information, and circuit details.
The dataset dimensions include variables like time, speed, lap position, and driver information.

4.Describe how the questions/approaches will be used:
The team plans to use data visualization techniques to explore and answer the research questions.
 Key methods include:
-Bar chart or time line showing race winners over the past four years, by annotating each bar with drivers name and year of the race
-Donut/pie chart to show the distribution
-Line plots for showing distance and speed on x-axis and y-axis respectively to show speed varies over the course of a lap
-scatter plot for showing pit stops, laps and final race position

5. Is there anything unclear:
The range/time period of the data is unclear. 

6.Constructive feedback:
-If one of the questions can shown some animation effect
-The project is good and has almost given insight on all the aspect of each question.

7.What aspect of the project are you most interested and looking forward to see highlighted:
-What are the main attributes which affect the outcome of the race. Does the the driver play the primary role or things like pitstops, circuits and technical aspects also play a significant role in it.
-Also how the lap times changes over the course of a race.

8.Feedback on issues:
- More clarity on the time range of the data if mentioned as historical and if you're focusing on a particular set of period.

**Comment by sindhugoshika** [comment]
Hello Team,

Thank you for your feedback.

Regarding #5, since we are working with a live dataset, the time period may vary. We appreciate your input and will ensure that our visualizations include animations to better present the data, as well as address your suggested question.

Thank you,
Team Pixels and Patterns
