### ISSUE TITLE
Peer Review by DataWaves Team

### ISSUE THREAD

**Issue by iam-ajeetsingh** [INFO-526-FA24/project-2-pixels-patterns#3]
1. **This peer review is submitted by the ‘DataWaves’ team**. The team member names and github ids are as follows: 

| **Full Names**          | **GitHub IDs**    |
|-----------------------------|-----------------------------|
| Saharsh Bhave          | Saharsh-Bhave         |
| LIBIN N George        |            libin-n-g          |
| Ajeet Singh               |  iam-ajeetsingh          |
| Navyashree Madhu  |    NavyasreeMadhu14 |

**2. Describe the goal of the project.**
- The project focuses on analyzing and visualizing Formula 1 race data using the f1DataR package, which provides access to historical race results, driver information, and circuit details. This project offers a deeper understanding of race outcomes, driver performance, and trends across different seasons, with a particular focus on specific Grand Prix events.

**3. Describe the data used or collected.**
- The FastF1 dataset is an open-source data library designed for motorsport analysis, offering telemetry, race lap data, sector times, pit stop events, and positional data for every Formula 1 race. The dataset dimensions include variables like time, speed, lap position, and driver information, making it possible to carry out detailed performance comparisons.

**4. Describe how the research question will be answered, e.g. what approaches / methods will be used.**

   - **For question 1:** By visualizing constructor wins, the analysis highlights which teams have excelled on this circuit. Create a bar chart or timeline showing the race winners over the past four years. Annotate each bar with the driver’s name, constructor, and the year of the race. Use a donut or pie chart to show the distribution of wins by constructors across the four years, highlighting team dominance.
  - **For question 2:** Create a line plot with distance on the x-axis and speed on the y-axis to show how speed varies over the course of a lap. Use color to represent throttle usage. Overlay key circuit sections (e.g., straights, corners, DRS zones) on the plot to provide additional context.
  - **For question 3:** A line plot showing lap time trends is highly visual and engaging, allowing viewers to easily track improvements over time. Faceted plots for circuit types enable intuitive comparisons, adding depth to the analysis.
  - **For question 4:** A scatter plot showing pit stop laps versus final race positions, annotated with key drivers and teams, provides a clear and compelling way to communicate the story of strategic impact in a race.

**5. Is there anything that is unclear from the proposal?**
- The team’s proposal is quite clear covering every aspect of the project required.

**6. Provide constructive feedback on how the team might be able to improve their project.**

- The team should consider providing a more detailed methodology that outlines the steps and techniques they plan to use for data analysis and visualization to answer each research question.
- The team should also include the data validation and cleaning processes in the proposal, including strategies for handling missing data, outliers, or inconsistencies in the dataset.
- While the proposal includes the weekly plan, it could be more detailed with specific due dates for each phase of the project. The project timeline is actually 7 weeks but your proposal specifies a plan for 4 weeks only. Adding specific dates to the plan will help in tracking progress.  

**7. What aspect of this project are you most interested in and would like to see highlighted in the presentation?**
- We are looking forward to the presentation of this interesting topic, especially how do each F1 team’s lap times improve over the course of the race, and how do these improvements compare across different circuit types. It is also interesting to know the relationship between pit stop timing and overall race position for top teams. 

**8. Provide constructive feedback on any issues with file and/or code organization.**
- You can also add the column name, the datatype of the column, and a small description of the data each column represents in a table format. This makes it easier to understand the data. 
- The number of rows and columns is missing in the data description.
- The Plan of Attack can be split further separating each question as different rows and assigning it to different people to make sure of parallel development of the project. 
- The plan of attack can also divide the write-up and presentation as different task. 

**9. (Optional) Any further comments or feedback?**
- You can use the Pacman package to install and load the dependencies. 
- For example,  You can also add an if condition which runs setup_fastf1() only once, then it will be easier to reproduce the project. 
```{r}
#| label: load-packages
if (!requireNamespace("pacman", quietly = TRUE)) {
    install.packages("pacman")  # Install pacman if not already installed
}
library(pacman)
pacman::p_load(ggplot2, dplyr, tidyr, 
               gridExtra, patchwork, grid,
               jpeg, showtext, tidyverse)

```

**Comment by sanjeevtejap** [comment]
All the mentioned changes were made to the Proposal file.
Thank you for all the suggestions and your time in reviewing the file.
We will definitely consider the visualisation techniques you guys mentioned.
