### ISSUE TITLE
instructor review

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-pixels-patterns#4]
Hello team Pixels Patterns - 

After review of your proposal, I believe that you team is set up for success.  Your data set should be able to answer the proposed questions and your analysis and visualizations should answer the questions. Please ensure that you work together to build or compliment each others tasks so that the story, write-up and poster are cohesive. 
 
One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |     3   |
| Proposal | 5         |    5    |
| Workflow | 1         |     1   |
| Teamwork | 1         |      1  |
| Total    | 10        |    10    |

**Comment by Sahana2699** [comment]
Thank you for your feedback on our proposal. We’re glad to know our dataset and analysis are on track. We will make sure to plan out the poster well, so it fits with our analysis and tells a clear story.

We appreciate your input and will continue working together to ensure everything aligns smoothly.
