### ISSUE TITLE
Review from Insight Spark

### ISSUE THREAD

**Issue by ronymacwan** [INFO-526-FA24/project-2-pixels-patterns#7]
Strength:
The poster effectively uses available data to tell an interesting story, particularly through the visualization of speed and throttle patterns. This provides valuable overview of the driver’s approach and performance.

Weakness:
There are fewer visualizations than expected. This limits the depth of the analysis. Additionally, the space could have been utilized more efficiently.

**Comment by Sahana2699** [comment]
Made changes to the poster.
