### ISSUE TITLE
Poster Review by Info Crew

### ISSUE THREAD

**Issue by tallapaneniv** [INFO-526-FA24/project-2-pixels-patterns#8]
Strength - explained data works good for plots 

Weakness -  plots are confusing, color pallet for each plot could be better

**Comment by sindhugoshika** [comment]
Thank you for your valuable feedback!

We’re glad that the data explanation worked well for the plots. We appreciate your comments regarding the plots being a bit confusing, and we’ve taken steps to improve the color palette for each plot to make them more clear and visually appealing.

Best regards,
Team Pixels and Patterns
