### ISSUE TITLE
Poster Review by Data Vizionaries

### ISSUE THREAD

**Issue by kapilparab** [INFO-526-FA24/project-2-pixels-patterns#9]
1. What is the good thing in the poster?

The topic is interesting and quite unique. The plot detailing the acceleration trend of drivers provides a glimpse of what it must be like to drive an F1 car. 

2. What do you think can/should be improved?

Color palette of plots can be improved to be more vibrant and colorblind friendly.

**Comment by sindhugoshika** [comment]
Thank you for your valuable feedback! We appreciate your positive comments on the topic and the plot detailing the acceleration trend of the drivers.

Regarding your suggestion about the color palette, we have made improvements and adjusted the colors to be more vibrant and colorblind-friendly.

Thanks again for your input!

Best regards,
Team Pixels and Patterns
